### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/comment-notifications#23]
## Acceptance Criteria

- Module works on SS4
- Beta tag is released

## Sub Tasks

- [x] #24 Add to Transifex and add configuration
- [x] #25 Convert to vendor module
- [x] Regression test

## Pull requests

- [x] #27
- [x] #26
- [x] https://github.com/colymba/GridFieldBulkEditingTools/pull/156
- [x] #28

**Comment by robbieaverill** [comment]
Beta 1 tagged: https://github.com/silverstripe/comment-notifications/releases/tag/2.0.0-beta1
