### ISSUE TITLE
Convert to vendor module

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/comment-notifications#25]

**Comment by robbieaverill** [comment]
colymba/GridFieldBulkEditingTools is referencing Object, which means the PHP 7.2 builds are failing. I've moved to blocked for now, until https://github.com/colymba/GridFieldBulkEditingTools/pull/156 is merged - then we can restart the Travis builds.

**Comment by tractorcow** [comment]
@robbieaverill can we shift to using gridfieldextensions? We were using both modules for the longest time, but we really should drop that module if we can help it. We may not be able to, but it'd be wise to look into it.

**Comment by robbieaverill** [comment]
I like the idea of reducing supported dependencies. It's really only used in the comments module's admin section, so if we can come up with a better way to handle it there then we probably can.

**Comment by robbieaverill** [comment]
The feature is basically the ability to select many or all comments from one of the three GridFields and delete, mark as spam or approve in bulk.

At a quick glance it doesn't look like gridfieldextensions has a component that would enable this type of bulk activity.

We could remove the dependency if we're happy to remove bulk management functionality from the comments module, otherwise we'd probably need to keep it.

**Comment by be2n** [comment]
As a general rule, 'bulk action' features are _very_ important from a content designer/ author perspective. I definitely wouldn't want to see the capability to apply a bulk action disappear from comment management which can be a daily activity for content authors.
